export const domainDefinitions = {
  users: {
    title: 'Users',
    description:
      'Manage account state and global roles. Sole farm owners must transfer ownership before deactivation.',
    item: 'user',
    empty: 'No users found.',
    fields: [
      { name: 'email', label: 'Email address', type: 'email', required: true },
      { name: 'role', label: 'System role', required: true },
      { name: 'status', label: 'Account status', required: true },
    ],
  },
  communities: {
    title: 'Communities',
    description: 'Coordinate members, shared resources, invitations, and farm relationships.',
    item: 'community',
    contextTypes: ['farm', 'community'],
    empty: 'Create a community to collaborate with nearby farmers.',
    fields: [
      { name: 'name', label: 'Community name', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'timezone', label: 'Timezone', defaultValue: 'Asia/Kolkata' },
      { name: 'state_code', label: 'State or Union Territory code' },
      { name: 'locality', label: 'Village or city' },
    ],
  },
  farms: {
    title: 'Farms',
    description: 'Manage farms, operating locations, members, and community links.',
    item: 'farm',
    contextTypes: ['farm', 'community'],
    empty: 'Add your first farm to begin planning fields and crop seasons.',
    fields: [
      { name: 'name', label: 'Farm name', required: true },
      { name: 'area_square_metres', label: 'Area (m²)', type: 'number', required: true },
      { name: 'timezone', label: 'Timezone', defaultValue: 'Asia/Kolkata' },
      { name: 'state_code', label: 'State or Union Territory code' },
      { name: 'district', label: 'District' },
      { name: 'taluk', label: 'Taluk / Tehsil' },
      { name: 'locality', label: 'Village or city' },
      { name: 'postal_code', label: 'Postal code' },
      { name: 'address', label: 'Address', type: 'textarea' },
    ],
  },
  fields: {
    title: 'Fields',
    description: 'Map field boundaries and optional management zones in square metres.',
    item: 'field',
    contextTypes: ['farm'],
    createRequiresContext: true,
    managePermission: 'manage_fields',
    empty: 'Create a field inside the active farm.',
    fields: [
      { name: 'farm_id', label: 'Farm', required: true, scope: true },
      { name: 'name', label: 'Field name', required: true },
      { name: 'area_square_metres', label: 'Area (m²)', type: 'number', required: true },
      { name: 'soil_type', label: 'Soil type' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  crops: {
    title: 'Crop catalogue',
    description: 'Use the global crop catalogue or create clearly labelled farm-specific crops.',
    item: 'crop',
    contextTypes: ['farm'],
    createRequiresContext: true,
    managePermission: 'manage_crops',
    empty: 'No crop catalogue entries match this workspace.',
    fields: [
      { name: 'farm_id', label: 'Farm', scope: true },
      { name: 'name', label: 'Crop name', required: true },
      { name: 'scientific_name', label: 'Scientific name' },
      { name: 'category', label: 'Category' },
    ],
  },
  'crop-seasons': {
    title: 'Crop seasons',
    description: 'Plan a crop on a field or zone for a defined growing period.',
    item: 'crop season',
    contextTypes: ['farm'],
    requiresContext: true,
    managePermission: 'manage_crops',
    empty: 'Create a crop season to connect crops, field work, conditions, and harvests.',
    fields: [
      { name: 'farm_id', label: 'Farm', required: true, scope: true },
      { name: 'field_id', label: 'Field', required: true, optionsKey: 'fields' },
      { name: 'field_zone_id', label: 'Field zone (optional)', optionsKey: 'zones' },
      { name: 'crop_id', label: 'Crop', required: true, optionsKey: 'crops' },
      { name: 'crop_variety_id', label: 'Variety (optional)', optionsKey: 'varieties' },
      { name: 'name', label: 'Season name' },
      { name: 'starts_on', label: 'Starts on', type: 'date', required: true },
      { name: 'expected_ends_on', label: 'Expected end date', type: 'date' },
    ],
  },
  tasks: {
    title: 'Tasks',
    description: 'Plan field or community work, assign owners, and track completion.',
    item: 'task',
    contextTypes: ['farm', 'community'],
    createRequiresContext: true,
    managePermission: 'manage_tasks',
    empty: 'No tasks in the current workspace.',
    fields: [
      { name: 'title', label: 'Task title', required: true },
      {
        name: 'task_type',
        label: 'Task type',
        type: 'select',
        options: [
          'sowing',
          'planting',
          'fertilizing',
          'spraying',
          'irrigation',
          'ploughing',
          'cultivation',
          'weeding',
          'mowing',
          'harvesting',
          'soil_testing',
          'field_inspection',
          'machinery_maintenance',
          'custom',
        ],
        defaultValue: 'custom',
      },
      { name: 'farm_id', label: 'Farm', scope: true },
      { name: 'community_id', label: 'Community', scope: true },
      { name: 'field_id', label: 'Field', optionsKey: 'fields' },
      { name: 'crop_season_id', label: 'Crop season', optionsKey: 'seasons' },
      { name: 'assigned_to_user_id', label: 'Assignee', optionsKey: 'members' },
      { name: 'shared_resource_id', label: 'Shared resource', optionsKey: 'resources' },
      {
        name: 'priority',
        label: 'Priority',
        type: 'select',
        options: ['low', 'medium', 'high', 'urgent'],
        defaultValue: 'medium',
      },
      { name: 'starts_at', label: 'Planned start', type: 'datetime-local' },
      { name: 'due_at', label: 'Due date and time', type: 'datetime-local' },
      { name: 'materials', label: 'Materials', type: 'textarea' },
      { name: 'weather_warning', label: 'Weather warning', type: 'textarea' },
      { name: 'description', label: 'Notes', type: 'textarea' },
    ],
  },
  inventories: {
    title: 'Inventory',
    description: 'Track farm or community stock through auditable inventory movements.',
    item: 'inventory item',
    contextTypes: ['farm', 'community'],
    requiresContext: true,
    managePermission: 'manage_inventory',
    empty: 'Add seeds, inputs, materials, or other stock.',
    fields: [
      { name: 'name', label: 'Item name', required: true },
      { name: 'farm_id', label: 'Farm', scope: true },
      { name: 'community_id', label: 'Community', scope: true },
      { name: 'quantity', label: 'Opening quantity', type: 'number', required: true },
      { name: 'unit', label: 'Unit', defaultValue: 'unit' },
      { name: 'reorder_level', label: 'Low-stock threshold', type: 'number' },
    ],
  },
  resources: {
    title: 'Shared resources',
    description: 'Publish community equipment and manage its availability.',
    item: 'resource',
    contextTypes: ['community'],
    requiresContext: true,
    managePermission: 'manage_resources',
    empty: 'No shared equipment or resources are available.',
    fields: [
      { name: 'community_id', label: 'Community', required: true, scope: true },
      { name: 'name', label: 'Resource name', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      {
        name: 'requires_approval',
        label: 'Requires approval',
        type: 'checkbox',
        defaultValue: true,
      },
    ],
  },
  reservations: {
    title: 'Reservations',
    description: 'Request equipment in half-open time slots; approval checks prevent conflicts.',
    item: 'reservation',
    contextTypes: ['community'],
    requiresContext: true,
    editable: false,
    deletable: false,
    transitionPermission: 'manage_resources',
    empty: 'No reservation requests in this workspace.',
    fields: [
      { name: 'resource_id', label: 'Resource', required: true, optionsKey: 'resources' },
      { name: 'farm_id', label: 'Requesting farm (optional)', optionsKey: 'farms' },
      { name: 'field_id', label: 'Field (optional)', optionsKey: 'fields' },
      { name: 'starts_at', label: 'Starts at', type: 'datetime-local', required: true },
      { name: 'ends_at', label: 'Ends at', type: 'datetime-local', required: true },
      { name: 'purpose', label: 'Purpose', type: 'textarea' },
    ],
  },
}

export function makeInitialForm(definition) {
  return Object.fromEntries(
    definition.fields.map((field) => [
      field.name,
      field.defaultValue ?? (field.type === 'checkbox' ? false : ''),
    ]),
  )
}
