<?php

namespace Database\Seeders;

use App\Enums\ConditionType;
use App\Enums\PlantType;
use App\Enums\TaskType;
use App\Models\CatalogPlant;
use App\Models\Plant;
use App\Models\PlantCare;
use App\Support\PlantCareName;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocalPlantCatalogSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function (): void {
            $this->resetPlantRelatedData();

            foreach ($this->catalogEntries() as $entry) {
                $canonicalName = PlantCareName::normalize($entry['name']);

                $plantCare = PlantCare::query()->create([
                    'description' => $entry['description'],
                    'conditions' => $entry['conditions'],
                    'growing_duration_days' => $entry['growing_duration_days'],
                    'germinating_duration_days' => $entry['germinating_duration_days'],
                    'flowering_duration_days' => $entry['flowering_duration_days'],
                    'mature_duration_days' => $entry['mature_duration_days'],
                    'mature_duration_end_days' => $entry['mature_duration_end_days'],
                    'mature_end_duration_days' => $entry['mature_end_duration_days'],
                    'regenerating_duration_days' => $entry['regenerating_duration_days'],
                    'reusable' => $entry['reusable'],
                    'plant_name' => $entry['name'],
                    'canonical_name' => $canonicalName,
                    'task_type' => $entry['task_type'],
                    'plant_type' => $entry['plant_type'],
                    'condition' => ConditionType::Planted->value,
                    'watering_interval_days' => $entry['watering_interval_days'],
                    'fertilizing_interval_days' => $entry['fertilizing_interval_days'],
                    'pest_check_interval_days' => $entry['pest_check_interval_days'],
                    'rain_skip_threshold_mm' => $entry['rain_skip_threshold_mm'],
                    'frost_temp_threshold_c' => $entry['frost_temp_threshold_c'],
                    'heat_extra_water_temp_c' => $entry['heat_extra_water_temp_c'],
                    'wind_protection_kmh' => $entry['wind_protection_kmh'],
                    'source_provider' => 'local',
                    'source_quality' => 'partial',
                    'source_perenual_species_id' => null,
                    'source_common_name' => $entry['name'],
                    'source_scientific_name' => $entry['source_scientific_name'],
                    'source_family' => $entry['source_family'],
                    'source_image_url' => null,
                ]);

                CatalogPlant::query()->create([
                    'name' => $entry['name'],
                    'canonical_name' => $canonicalName,
                    'plant_type' => $entry['plant_type'],
                    'fk_plant_care_id' => $plantCare->id,
                    'description' => $entry['description'],
                    'source_provider' => 'local',
                    'source_quality' => 'partial',
                    'source_scientific_name' => $entry['source_scientific_name'],
                    'source_family' => $entry['source_family'],
                    'source_image_url' => null,
                    'metadata' => [
                        'catalog_scope' => 'local_top_20',
                        'curation_mode' => 'manual',
                    ],
                ]);
            }
        });
    }

    private function resetPlantRelatedData(): void
    {
        $plantIds = Plant::query()->pluck('id');

        if ($plantIds->isNotEmpty()) {
            $taskIds = DB::table('tasks')
                ->where(function ($query) use ($plantIds): void {
                    $query
                        ->whereIn('plant_id', $plantIds)
                        ->orWhereIn('fk_plant_id', $plantIds);
                })
                ->pluck('id');

            if ($taskIds->isNotEmpty()) {
                DB::table('used_on')->whereIn('fk_task_id', $taskIds)->delete();
                DB::table('harvest_records')->whereIn('task_id', $taskIds)->delete();
                DB::table('tasks')->whereIn('id', $taskIds)->delete();
            }

            DB::table('harvest_records')->whereIn('plant_id', $plantIds)->delete();

            DB::table('plant_condition_history')
                ->where(function ($query) use ($plantIds): void {
                    $query
                        ->whereIn('plant_id', $plantIds)
                        ->orWhereIn('fk_plant_id', $plantIds);
                })
                ->delete();

            DB::table('rotation_history')
                ->whereIn('fk_plant_id', $plantIds)
                ->delete();

            Plant::query()->delete();
        }

        CatalogPlant::query()->delete();

        PlantCare::query()
            ->whereDoesntHave('plants')
            ->whereDoesntHave('catalogPlants')
            ->delete();
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function catalogEntries(): array
    {
        return [
            [
                'name' => 'Tomato',
                'description' => 'Tomato is a warm-season fruiting vegetable that prefers full sun, regular watering, staking support, and nutrient-rich well-drained soil.',
                'conditions' => 'Full sun, fertile well-drained soil, steady deep watering, support for climbing growth, and protection from cold nights.',
                'growing_duration_days' => 85,
                'germinating_duration_days' => 8,
                'flowering_duration_days' => 30,
                'mature_duration_days' => 60,
                'mature_duration_end_days' => 35,
                'mature_end_duration_days' => 35,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 3,
                'fertilizing_interval_days' => 14,
                'pest_check_interval_days' => 5,
                'rain_skip_threshold_mm' => 8.0,
                'frost_temp_threshold_c' => 10.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 35.0,
                'source_scientific_name' => 'Solanum lycopersicum',
                'source_family' => 'Solanaceae',
            ],
            [
                'name' => 'Cucumber',
                'description' => 'Cucumber is a vigorous warm-season vine that needs warm soil, frequent moisture, and regular harvesting for continued production.',
                'conditions' => 'Full sun, rich loose soil, trellis support or open spreading space, and even moisture without prolonged dryness.',
                'growing_duration_days' => 65,
                'germinating_duration_days' => 7,
                'flowering_duration_days' => 24,
                'mature_duration_days' => 50,
                'mature_duration_end_days' => 20,
                'mature_end_duration_days' => 20,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 2,
                'fertilizing_interval_days' => 14,
                'pest_check_interval_days' => 5,
                'rain_skip_threshold_mm' => 10.0,
                'frost_temp_threshold_c' => 10.0,
                'heat_extra_water_temp_c' => 29.0,
                'wind_protection_kmh' => 30.0,
                'source_scientific_name' => 'Cucumis sativus',
                'source_family' => 'Cucurbitaceae',
            ],
            [
                'name' => 'Lettuce',
                'description' => 'Lettuce is a quick cool-season leafy vegetable grown for tender leaves and best quality under steady moisture and mild temperatures.',
                'conditions' => 'Full sun to light shade, cool weather, loose fertile soil, and consistent moisture to prevent bitterness and bolting.',
                'growing_duration_days' => 50,
                'germinating_duration_days' => 6,
                'flowering_duration_days' => 0,
                'mature_duration_days' => 35,
                'mature_duration_end_days' => 14,
                'mature_end_duration_days' => 14,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 2,
                'fertilizing_interval_days' => 14,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 8.0,
                'frost_temp_threshold_c' => 1.0,
                'heat_extra_water_temp_c' => 26.0,
                'wind_protection_kmh' => 35.0,
                'source_scientific_name' => 'Lactuca sativa',
                'source_family' => 'Asteraceae',
            ],
            [
                'name' => 'Carrot',
                'description' => 'Carrot is a cool-season root vegetable that develops best in deep loose soil with even moisture and low fresh-manure pressure.',
                'conditions' => 'Full sun, stone-free loose soil, moderate regular watering, and careful thinning for straight root development.',
                'growing_duration_days' => 75,
                'germinating_duration_days' => 14,
                'flowering_duration_days' => 0,
                'mature_duration_days' => 70,
                'mature_duration_end_days' => 14,
                'mature_end_duration_days' => 14,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 4,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 9.0,
                'frost_temp_threshold_c' => -2.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 40.0,
                'source_scientific_name' => 'Daucus carota subsp. sativus',
                'source_family' => 'Apiaceae',
            ],
            [
                'name' => 'Potato',
                'description' => 'Potato is a tuber-forming vegetable that benefits from hilling, steady moisture, and balanced nutrition while the canopy is actively growing.',
                'conditions' => 'Full sun, fertile loose soil, regular hilling, and deep watering without persistent waterlogging.',
                'growing_duration_days' => 110,
                'germinating_duration_days' => 14,
                'flowering_duration_days' => 28,
                'mature_duration_days' => 90,
                'mature_duration_end_days' => 21,
                'mature_end_duration_days' => 21,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 4,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 10.0,
                'frost_temp_threshold_c' => 2.0,
                'heat_extra_water_temp_c' => 28.0,
                'wind_protection_kmh' => 45.0,
                'source_scientific_name' => 'Solanum tuberosum',
                'source_family' => 'Solanaceae',
            ],
            [
                'name' => 'Onion',
                'description' => 'Onion is a bulb vegetable that prefers open sun, moderate moisture, and good airflow to build healthy bulbs without rot pressure.',
                'conditions' => 'Full sun, free-draining soil, modest fertility, and lighter watering as bulbs approach maturity.',
                'growing_duration_days' => 110,
                'germinating_duration_days' => 10,
                'flowering_duration_days' => 0,
                'mature_duration_days' => 90,
                'mature_duration_end_days' => 21,
                'mature_end_duration_days' => 21,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 5,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 10,
                'rain_skip_threshold_mm' => 8.0,
                'frost_temp_threshold_c' => -3.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 40.0,
                'source_scientific_name' => 'Allium cepa',
                'source_family' => 'Amaryllidaceae',
            ],
            [
                'name' => 'Garlic',
                'description' => 'Garlic is a long-season bulb vegetable commonly grown through cool weather and finished with reduced irrigation near harvest.',
                'conditions' => 'Full sun, fertile draining soil, winter mulch where needed, and restrained watering once bulbs size up.',
                'growing_duration_days' => 240,
                'germinating_duration_days' => 14,
                'flowering_duration_days' => 0,
                'mature_duration_days' => 210,
                'mature_duration_end_days' => 21,
                'mature_end_duration_days' => 21,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 7,
                'fertilizing_interval_days' => 30,
                'pest_check_interval_days' => 10,
                'rain_skip_threshold_mm' => 8.0,
                'frost_temp_threshold_c' => -10.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 45.0,
                'source_scientific_name' => 'Allium sativum',
                'source_family' => 'Amaryllidaceae',
            ],
            [
                'name' => 'Spinach',
                'description' => 'Spinach is a cool-season leafy vegetable grown for rapid tender harvests and it performs best before sustained heat arrives.',
                'conditions' => 'Full sun to part shade, rich soil, steady moisture, and cool temperatures to delay bolting.',
                'growing_duration_days' => 45,
                'germinating_duration_days' => 7,
                'flowering_duration_days' => 0,
                'mature_duration_days' => 35,
                'mature_duration_end_days' => 10,
                'mature_end_duration_days' => 10,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 2,
                'fertilizing_interval_days' => 14,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 8.0,
                'frost_temp_threshold_c' => -4.0,
                'heat_extra_water_temp_c' => 24.0,
                'wind_protection_kmh' => 35.0,
                'source_scientific_name' => 'Spinacia oleracea',
                'source_family' => 'Amaranthaceae',
            ],
            [
                'name' => 'Bell Pepper',
                'description' => 'Bell Pepper is a warm-season fruiting vegetable that needs warmth, stable moisture, and balanced feeding during flowering and fruit set.',
                'conditions' => 'Full sun, sheltered warm site, rich soil, and even watering to avoid blossom drop or misshapen fruit.',
                'growing_duration_days' => 95,
                'germinating_duration_days' => 14,
                'flowering_duration_days' => 35,
                'mature_duration_days' => 75,
                'mature_duration_end_days' => 30,
                'mature_end_duration_days' => 30,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 3,
                'fertilizing_interval_days' => 14,
                'pest_check_interval_days' => 6,
                'rain_skip_threshold_mm' => 8.0,
                'frost_temp_threshold_c' => 10.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 35.0,
                'source_scientific_name' => 'Capsicum annuum',
                'source_family' => 'Solanaceae',
            ],
            [
                'name' => 'Zucchini',
                'description' => 'Zucchini is a productive summer squash that needs rich soil, generous moisture, and frequent harvesting of young fruit.',
                'conditions' => 'Full sun, fertile soil, open airflow, and steady summer watering during rapid vegetative and fruit growth.',
                'growing_duration_days' => 60,
                'germinating_duration_days' => 7,
                'flowering_duration_days' => 20,
                'mature_duration_days' => 45,
                'mature_duration_end_days' => 21,
                'mature_end_duration_days' => 21,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 3,
                'fertilizing_interval_days' => 14,
                'pest_check_interval_days' => 5,
                'rain_skip_threshold_mm' => 10.0,
                'frost_temp_threshold_c' => 10.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 30.0,
                'source_scientific_name' => 'Cucurbita pepo',
                'source_family' => 'Cucurbitaceae',
            ],
            [
                'name' => 'Pumpkin',
                'description' => 'Pumpkin is a long-season vining squash grown for large fruit and it performs best with warm soil, space, and deep summer watering.',
                'conditions' => 'Full sun, nutrient-rich soil, wide spacing for vines, and deep watering during fruit fill and dry weather.',
                'growing_duration_days' => 105,
                'germinating_duration_days' => 8,
                'flowering_duration_days' => 30,
                'mature_duration_days' => 90,
                'mature_duration_end_days' => 28,
                'mature_end_duration_days' => 28,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Vegetable->value,
                'watering_interval_days' => 4,
                'fertilizing_interval_days' => 14,
                'pest_check_interval_days' => 6,
                'rain_skip_threshold_mm' => 10.0,
                'frost_temp_threshold_c' => 10.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 30.0,
                'source_scientific_name' => 'Cucurbita maxima',
                'source_family' => 'Cucurbitaceae',
            ],
            [
                'name' => 'Pea',
                'description' => 'Pea is a cool-season legume that climbs or sprawls lightly, fixes nitrogen, and prefers mild weather with regular moisture.',
                'conditions' => 'Full sun, cool temperatures, support for climbing types, and moderate fertile soil with even moisture.',
                'growing_duration_days' => 70,
                'germinating_duration_days' => 9,
                'flowering_duration_days' => 25,
                'mature_duration_days' => 55,
                'mature_duration_end_days' => 14,
                'mature_end_duration_days' => 14,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Legume->value,
                'watering_interval_days' => 3,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 9.0,
                'frost_temp_threshold_c' => -2.0,
                'heat_extra_water_temp_c' => 27.0,
                'wind_protection_kmh' => 35.0,
                'source_scientific_name' => 'Pisum sativum',
                'source_family' => 'Fabaceae',
            ],
            [
                'name' => 'Bean',
                'description' => 'Bean is a warm-season legume that prefers warm soil, moderate fertility, and frequent picking to keep pod production going.',
                'conditions' => 'Full sun, warm soil, moderate feeding, and even watering while avoiding prolonged wet foliage.',
                'growing_duration_days' => 60,
                'germinating_duration_days' => 8,
                'flowering_duration_days' => 20,
                'mature_duration_days' => 50,
                'mature_duration_end_days' => 14,
                'mature_end_duration_days' => 14,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Legume->value,
                'watering_interval_days' => 3,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 6,
                'rain_skip_threshold_mm' => 8.0,
                'frost_temp_threshold_c' => 8.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 35.0,
                'source_scientific_name' => 'Phaseolus vulgaris',
                'source_family' => 'Fabaceae',
            ],
            [
                'name' => 'Strawberry',
                'description' => 'Strawberry is a low perennial fruit crop that benefits from mulch, steady moisture, and renewal after several productive seasons.',
                'conditions' => 'Full sun, fertile well-drained soil, mulch under fruit, and consistent moisture during flowering and fruiting.',
                'growing_duration_days' => 120,
                'germinating_duration_days' => 21,
                'flowering_duration_days' => 25,
                'mature_duration_days' => 90,
                'mature_duration_end_days' => 35,
                'mature_end_duration_days' => 35,
                'regenerating_duration_days' => 30,
                'reusable' => true,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Berry->value,
                'watering_interval_days' => 3,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 10.0,
                'frost_temp_threshold_c' => -5.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 40.0,
                'source_scientific_name' => 'Fragaria x ananassa',
                'source_family' => 'Rosaceae',
            ],
            [
                'name' => 'Basil',
                'description' => 'Basil is a tender aromatic herb that thrives in warmth, regular pinching, and moderate feeding for leafy growth.',
                'conditions' => 'Full sun, warm sheltered position, fertile soil, and consistent moisture without cold stress or soggy roots.',
                'growing_duration_days' => 50,
                'germinating_duration_days' => 7,
                'flowering_duration_days' => 35,
                'mature_duration_days' => 30,
                'mature_duration_end_days' => 21,
                'mature_end_duration_days' => 21,
                'regenerating_duration_days' => 14,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Herb->value,
                'watering_interval_days' => 4,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 6.0,
                'frost_temp_threshold_c' => 10.0,
                'heat_extra_water_temp_c' => 29.0,
                'wind_protection_kmh' => 30.0,
                'source_scientific_name' => 'Ocimum basilicum',
                'source_family' => 'Lamiaceae',
            ],
            [
                'name' => 'Dill',
                'description' => 'Dill is a soft annual herb grown for foliage and seed, and it does best in open sun with moderate feeding and mild weather.',
                'conditions' => 'Full sun, light soil, moderate watering, and minimal root disturbance after establishment.',
                'growing_duration_days' => 55,
                'germinating_duration_days' => 10,
                'flowering_duration_days' => 40,
                'mature_duration_days' => 45,
                'mature_duration_end_days' => 14,
                'mature_end_duration_days' => 14,
                'regenerating_duration_days' => 0,
                'reusable' => false,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Herb->value,
                'watering_interval_days' => 4,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 7.0,
                'frost_temp_threshold_c' => 2.0,
                'heat_extra_water_temp_c' => 28.0,
                'wind_protection_kmh' => 35.0,
                'source_scientific_name' => 'Anethum graveolens',
                'source_family' => 'Apiaceae',
            ],
            [
                'name' => 'Parsley',
                'description' => 'Parsley is a slow-starting herb that can be harvested repeatedly once established and appreciates regular moisture in fertile soil.',
                'conditions' => 'Full sun to part shade, rich moisture-retentive soil, and repeated outer-stem harvests to encourage fresh growth.',
                'growing_duration_days' => 90,
                'germinating_duration_days' => 21,
                'flowering_duration_days' => 0,
                'mature_duration_days' => 75,
                'mature_duration_end_days' => 30,
                'mature_end_duration_days' => 30,
                'regenerating_duration_days' => 21,
                'reusable' => true,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Herb->value,
                'watering_interval_days' => 4,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 7.0,
                'frost_temp_threshold_c' => -3.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 35.0,
                'source_scientific_name' => 'Petroselinum crispum',
                'source_family' => 'Apiaceae',
            ],
            [
                'name' => 'Mint',
                'description' => 'Mint is a vigorous perennial herb best grown with containment, regular cutting, and close moisture monitoring during hot spells.',
                'conditions' => 'Full sun to part shade, moist fertile soil, and routine trimming to keep fresh aromatic growth coming.',
                'growing_duration_days' => 80,
                'germinating_duration_days' => 15,
                'flowering_duration_days' => 60,
                'mature_duration_days' => 60,
                'mature_duration_end_days' => 30,
                'mature_end_duration_days' => 30,
                'regenerating_duration_days' => 21,
                'reusable' => true,
                'task_type' => TaskType::Watering->value,
                'plant_type' => PlantType::Herb->value,
                'watering_interval_days' => 3,
                'fertilizing_interval_days' => 21,
                'pest_check_interval_days' => 10,
                'rain_skip_threshold_mm' => 8.0,
                'frost_temp_threshold_c' => -10.0,
                'heat_extra_water_temp_c' => 30.0,
                'wind_protection_kmh' => 35.0,
                'source_scientific_name' => 'Mentha x piperita',
                'source_family' => 'Lamiaceae',
            ],
            [
                'name' => 'Apple Tree',
                'description' => 'Apple Tree is a woody perennial fruit crop that needs seasonal pruning, deep watering in dry periods, and regular disease monitoring.',
                'conditions' => 'Full sun, open airflow, deep well-drained soil, seasonal pruning, and careful pest and scab monitoring across the season.',
                'growing_duration_days' => 240,
                'germinating_duration_days' => 21,
                'flowering_duration_days' => 20,
                'mature_duration_days' => 160,
                'mature_duration_end_days' => 60,
                'mature_end_duration_days' => 60,
                'regenerating_duration_days' => 60,
                'reusable' => true,
                'task_type' => TaskType::Spray->value,
                'plant_type' => PlantType::Tree->value,
                'watering_interval_days' => 7,
                'fertilizing_interval_days' => 45,
                'pest_check_interval_days' => 10,
                'rain_skip_threshold_mm' => 12.0,
                'frost_temp_threshold_c' => -15.0,
                'heat_extra_water_temp_c' => 32.0,
                'wind_protection_kmh' => 55.0,
                'source_scientific_name' => 'Malus domestica',
                'source_family' => 'Rosaceae',
            ],
            [
                'name' => 'Rose',
                'description' => 'Rose is a woody ornamental perennial that benefits from deep watering, periodic feeding, deadheading, and consistent disease inspection.',
                'conditions' => 'Full sun, fertile draining soil, seasonal pruning, strong airflow, and close black spot and pest monitoring.',
                'growing_duration_days' => 180,
                'germinating_duration_days' => 21,
                'flowering_duration_days' => 45,
                'mature_duration_days' => 130,
                'mature_duration_end_days' => 60,
                'mature_end_duration_days' => 60,
                'regenerating_duration_days' => 30,
                'reusable' => true,
                'task_type' => TaskType::Spray->value,
                'plant_type' => PlantType::Shrub->value,
                'watering_interval_days' => 5,
                'fertilizing_interval_days' => 30,
                'pest_check_interval_days' => 7,
                'rain_skip_threshold_mm' => 8.0,
                'frost_temp_threshold_c' => -8.0,
                'heat_extra_water_temp_c' => 32.0,
                'wind_protection_kmh' => 45.0,
                'source_scientific_name' => 'Rosa spp.',
                'source_family' => 'Rosaceae',
            ],
        ];
    }
}
