<?php

namespace App\Services\Plant;

use App\Enums\ConditionType;
use App\Enums\PlantType;
use App\Enums\TaskType;
use App\Models\Plant;

class PlantCareDefaults
{
    private const PROFILE_DEFAULTS = [
        'general' => [
            'profile_label' => 'general plant',
            'conditions' => 'Moderate light, balanced moisture, routine feeding, and weather-aware protection.',
            'growing_duration_days' => 60,
            'germinating_duration_days' => 12,
            'flowering_duration_days' => 21,
            'mature_duration_days' => 45,
            'mature_duration_end_days' => 21,
            'regenerating_duration_days' => 0,
            'reusable' => false,
            'watering_interval_days' => 4,
            'fertilizing_interval_days' => 21,
            'pest_check_interval_days' => 7,
            'rain_skip_threshold_mm' => 8.0,
            'frost_temp_threshold_c' => 1.0,
            'heat_extra_water_temp_c' => 30.0,
            'wind_protection_kmh' => 40.0,
        ],
        'sparse_unknown' => [
            'profile_label' => 'unknown plant',
            'conditions' => 'Moderate light, conservative watering, and routine monitoring until stronger care data is available.',
            'growing_duration_days' => 70,
            'germinating_duration_days' => 14,
            'flowering_duration_days' => 21,
            'mature_duration_days' => 50,
            'mature_duration_end_days' => 21,
            'regenerating_duration_days' => 0,
            'reusable' => false,
            'watering_interval_days' => 5,
            'fertilizing_interval_days' => 28,
            'pest_check_interval_days' => 8,
            'rain_skip_threshold_mm' => 9.0,
            'frost_temp_threshold_c' => 1.0,
            'heat_extra_water_temp_c' => 31.0,
            'wind_protection_kmh' => 42.0,
        ],
        'berry' => [
            'profile_label' => 'berry plant',
            'conditions' => 'Full to partial sun, evenly moist soil, seasonal feeding, and close fruiting-season monitoring.',
            'growing_duration_days' => 110,
            'germinating_duration_days' => 16,
            'flowering_duration_days' => 24,
            'mature_duration_days' => 80,
            'mature_duration_end_days' => 28,
            'regenerating_duration_days' => 28,
            'reusable' => true,
            'watering_interval_days' => 4,
            'fertilizing_interval_days' => 28,
            'pest_check_interval_days' => 7,
            'rain_skip_threshold_mm' => 9.0,
            'frost_temp_threshold_c' => -4.0,
            'heat_extra_water_temp_c' => 30.0,
            'wind_protection_kmh' => 38.0,
        ],
        'vegetable' => [
            'profile_label' => 'vegetable crop',
            'conditions' => 'Full to partial sun, steady moisture, regular feeding, and close weather monitoring.',
            'growing_duration_days' => 50,
            'germinating_duration_days' => 8,
            'flowering_duration_days' => 18,
            'mature_duration_days' => 35,
            'mature_duration_end_days' => 14,
            'regenerating_duration_days' => 0,
            'reusable' => false,
            'watering_interval_days' => 3,
            'fertilizing_interval_days' => 14,
            'pest_check_interval_days' => 6,
            'rain_skip_threshold_mm' => 8.0,
            'frost_temp_threshold_c' => 10.0,
            'heat_extra_water_temp_c' => 29.0,
            'wind_protection_kmh' => 38.0,
        ],
        'flower' => [
            'profile_label' => 'flowering ornamental',
            'conditions' => 'Balanced light, even moisture, modest feeding, and routine deadheading or bloom checks.',
            'growing_duration_days' => 75,
            'germinating_duration_days' => 12,
            'flowering_duration_days' => 32,
            'mature_duration_days' => 85,
            'mature_duration_end_days' => 35,
            'regenerating_duration_days' => 24,
            'reusable' => false,
            'watering_interval_days' => 5,
            'fertilizing_interval_days' => 28,
            'pest_check_interval_days' => 8,
            'rain_skip_threshold_mm' => 8.0,
            'frost_temp_threshold_c' => 4.0,
            'heat_extra_water_temp_c' => 31.0,
            'wind_protection_kmh' => 34.0,
        ],
        'herb' => [
            'profile_label' => 'herb',
            'conditions' => 'Bright light, moderate moisture, lighter feeding, and regular pest checks.',
            'growing_duration_days' => 45,
            'germinating_duration_days' => 10,
            'flowering_duration_days' => 24,
            'mature_duration_days' => 40,
            'mature_duration_end_days' => 20,
            'regenerating_duration_days' => 21,
            'reusable' => false,
            'watering_interval_days' => 4,
            'fertilizing_interval_days' => 21,
            'pest_check_interval_days' => 7,
            'rain_skip_threshold_mm' => 7.0,
            'frost_temp_threshold_c' => 1.0,
            'heat_extra_water_temp_c' => 30.0,
            'wind_protection_kmh' => 35.0,
        ],
        'legume' => [
            'profile_label' => 'legume crop',
            'conditions' => 'Full sun, steady moisture, moderate feeding, and frequent pest monitoring.',
            'growing_duration_days' => 55,
            'germinating_duration_days' => 8,
            'flowering_duration_days' => 16,
            'mature_duration_days' => 35,
            'mature_duration_end_days' => 14,
            'regenerating_duration_days' => 0,
            'reusable' => false,
            'watering_interval_days' => 3,
            'fertilizing_interval_days' => 18,
            'pest_check_interval_days' => 6,
            'rain_skip_threshold_mm' => 8.0,
            'frost_temp_threshold_c' => 1.0,
            'heat_extra_water_temp_c' => 30.0,
            'wind_protection_kmh' => 40.0,
        ],
        'cereal' => [
            'profile_label' => 'cereal crop',
            'conditions' => 'Open sun, moderate watering, periodic feeding, and wind-aware protection.',
            'growing_duration_days' => 70,
            'germinating_duration_days' => 8,
            'flowering_duration_days' => 14,
            'mature_duration_days' => 40,
            'mature_duration_end_days' => 12,
            'regenerating_duration_days' => 0,
            'reusable' => false,
            'watering_interval_days' => 4,
            'fertilizing_interval_days' => 21,
            'pest_check_interval_days' => 7,
            'rain_skip_threshold_mm' => 9.0,
            'frost_temp_threshold_c' => 0.0,
            'heat_extra_water_temp_c' => 31.0,
            'wind_protection_kmh' => 55.0,
        ],
        'forage' => [
            'profile_label' => 'forage crop',
            'conditions' => 'Open light, moderate moisture, broad weather tolerance, and recurring regrowth checks.',
            'growing_duration_days' => 60,
            'germinating_duration_days' => 10,
            'flowering_duration_days' => 18,
            'mature_duration_days' => 45,
            'mature_duration_end_days' => 21,
            'regenerating_duration_days' => 21,
            'reusable' => true,
            'watering_interval_days' => 5,
            'fertilizing_interval_days' => 28,
            'pest_check_interval_days' => 8,
            'rain_skip_threshold_mm' => 10.0,
            'frost_temp_threshold_c' => -1.0,
            'heat_extra_water_temp_c' => 31.0,
            'wind_protection_kmh' => 50.0,
        ],
        'oilseed' => [
            'profile_label' => 'oilseed crop',
            'conditions' => 'Full sun, moderate moisture, periodic feeding, and wind-aware support.',
            'growing_duration_days' => 80,
            'germinating_duration_days' => 10,
            'flowering_duration_days' => 20,
            'mature_duration_days' => 50,
            'mature_duration_end_days' => 20,
            'regenerating_duration_days' => 0,
            'reusable' => false,
            'watering_interval_days' => 4,
            'fertilizing_interval_days' => 21,
            'pest_check_interval_days' => 7,
            'rain_skip_threshold_mm' => 9.0,
            'frost_temp_threshold_c' => 1.0,
            'heat_extra_water_temp_c' => 31.0,
            'wind_protection_kmh' => 45.0,
        ],
        'fruit' => [
            'profile_label' => 'fruiting perennial',
            'conditions' => 'Good light, deeper watering, periodic feeding, and seasonal weather protection.',
            'growing_duration_days' => 120,
            'germinating_duration_days' => 18,
            'flowering_duration_days' => 30,
            'mature_duration_days' => 75,
            'mature_duration_end_days' => 30,
            'regenerating_duration_days' => 30,
            'reusable' => true,
            'watering_interval_days' => 7,
            'fertilizing_interval_days' => 30,
            'pest_check_interval_days' => 7,
            'rain_skip_threshold_mm' => 10.0,
            'frost_temp_threshold_c' => -2.0,
            'heat_extra_water_temp_c' => 32.0,
            'wind_protection_kmh' => 50.0,
        ],
        'shrub' => [
            'profile_label' => 'woody shrub',
            'conditions' => 'Full to partial sun, deep but spaced watering, seasonal feeding, and pruning-aware maintenance.',
            'growing_duration_days' => 160,
            'germinating_duration_days' => 18,
            'flowering_duration_days' => 36,
            'mature_duration_days' => 220,
            'mature_duration_end_days' => 90,
            'regenerating_duration_days' => 36,
            'reusable' => true,
            'watering_interval_days' => 6,
            'fertilizing_interval_days' => 35,
            'pest_check_interval_days' => 9,
            'rain_skip_threshold_mm' => 10.0,
            'frost_temp_threshold_c' => -6.0,
            'heat_extra_water_temp_c' => 32.0,
            'wind_protection_kmh' => 48.0,
        ],
        'tree' => [
            'profile_label' => 'woody tree',
            'conditions' => 'Open light, deeper watering during dry periods, low-frequency feeding, and seasonal pruning or inspection.',
            'growing_duration_days' => 220,
            'germinating_duration_days' => 21,
            'flowering_duration_days' => 28,
            'mature_duration_days' => 320,
            'mature_duration_end_days' => 120,
            'regenerating_duration_days' => 45,
            'reusable' => true,
            'watering_interval_days' => 7,
            'fertilizing_interval_days' => 45,
            'pest_check_interval_days' => 10,
            'rain_skip_threshold_mm' => 11.0,
            'frost_temp_threshold_c' => -8.0,
            'heat_extra_water_temp_c' => 32.0,
            'wind_protection_kmh' => 60.0,
        ],
        'ornamental' => [
            'profile_label' => 'ornamental plant',
            'conditions' => 'Balanced light, even moisture, modest feeding, and seasonal maintenance.',
            'growing_duration_days' => 80,
            'germinating_duration_days' => 12,
            'flowering_duration_days' => 30,
            'mature_duration_days' => 90,
            'mature_duration_end_days' => 45,
            'regenerating_duration_days' => 30,
            'reusable' => false,
            'watering_interval_days' => 5,
            'fertilizing_interval_days' => 28,
            'pest_check_interval_days' => 9,
            'rain_skip_threshold_mm' => 8.0,
            'frost_temp_threshold_c' => 4.0,
            'heat_extra_water_temp_c' => 31.0,
            'wind_protection_kmh' => 36.0,
        ],
        'vine' => [
            'profile_label' => 'vining plant',
            'conditions' => 'Good light, steady moisture, support for climbing growth, and routine monitoring.',
            'growing_duration_days' => 75,
            'germinating_duration_days' => 10,
            'flowering_duration_days' => 24,
            'mature_duration_days' => 55,
            'mature_duration_end_days' => 28,
            'regenerating_duration_days' => 21,
            'reusable' => false,
            'watering_interval_days' => 4,
            'fertilizing_interval_days' => 21,
            'pest_check_interval_days' => 7,
            'rain_skip_threshold_mm' => 8.0,
            'frost_temp_threshold_c' => 6.0,
            'heat_extra_water_temp_c' => 30.0,
            'wind_protection_kmh' => 32.0,
        ],
        'succulent' => [
            'profile_label' => 'succulent plant',
            'conditions' => 'Bright light, infrequent watering, sparse feeding, and protection from prolonged frost.',
            'growing_duration_days' => 90,
            'germinating_duration_days' => 14,
            'flowering_duration_days' => 20,
            'mature_duration_days' => 120,
            'mature_duration_end_days' => 60,
            'regenerating_duration_days' => 45,
            'reusable' => true,
            'watering_interval_days' => 10,
            'fertilizing_interval_days' => 45,
            'pest_check_interval_days' => 14,
            'rain_skip_threshold_mm' => 5.0,
            'frost_temp_threshold_c' => 8.0,
            'heat_extra_water_temp_c' => 34.0,
            'wind_protection_kmh' => 45.0,
        ],
        'woody_ornamental' => [
            'profile_label' => 'woody perennial ornamental',
            'conditions' => 'Balanced light, deeper watering, low feeding, and seasonal weather protection.',
            'growing_duration_days' => 180,
            'germinating_duration_days' => 21,
            'flowering_duration_days' => 45,
            'mature_duration_days' => 365,
            'mature_duration_end_days' => 120,
            'regenerating_duration_days' => 45,
            'reusable' => true,
            'watering_interval_days' => 7,
            'fertilizing_interval_days' => 45,
            'pest_check_interval_days' => 10,
            'rain_skip_threshold_mm' => 10.0,
            'frost_temp_threshold_c' => -5.0,
            'heat_extra_water_temp_c' => 32.0,
            'wind_protection_kmh' => 60.0,
        ],
        'tropical_indoor' => [
            'profile_label' => 'tropical or indoor plant',
            'conditions' => 'Bright indirect light, even moisture, lighter feeding, and protection from cold stress.',
            'growing_duration_days' => 75,
            'germinating_duration_days' => 14,
            'flowering_duration_days' => 30,
            'mature_duration_days' => 90,
            'mature_duration_end_days' => 45,
            'regenerating_duration_days' => 30,
            'reusable' => true,
            'watering_interval_days' => 6,
            'fertilizing_interval_days' => 30,
            'pest_check_interval_days' => 10,
            'rain_skip_threshold_mm' => 7.0,
            'frost_temp_threshold_c' => 8.0,
            'heat_extra_water_temp_c' => 30.0,
            'wind_protection_kmh' => 55.0,
        ],
    ];

    /**
     * @return array<string, mixed>
     */
    public function forPlant(
        Plant $plant,
        ?string $resolvedPlantName = null,
        string $profileGroup = 'general',
        ?PlantType $resolvedPlantType = null,
    ): array {
        $plantName = $resolvedPlantName ?: $plant->name;
        $group = self::PROFILE_DEFAULTS[$profileGroup] ?? self::PROFILE_DEFAULTS['general'];
        $plantType = $resolvedPlantType
            ?? ($plant->type instanceof PlantType ? $plant->type : PlantType::Herb);

        return [
            'description' => sprintf(
                '%s care profile generated from centralized %s defaults.',
                $plantName,
                $group['profile_label']
            ),
            'conditions' => $group['conditions'],
            'growing_duration_days' => $group['growing_duration_days'],
            'germinating_duration_days' => $group['germinating_duration_days'],
            'flowering_duration_days' => $group['flowering_duration_days'],
            'mature_duration_days' => $group['mature_duration_days'],
            'mature_duration_end_days' => $group['mature_duration_end_days'],
            'regenerating_duration_days' => $group['regenerating_duration_days'],
            'reusable' => $group['reusable'],
            'plant_type' => $plantType->value,
            'condition' => ConditionType::Planted->value,
            'plant_name' => $plantName,
            'task_type' => TaskType::Watering->value,
            'watering_interval_days' => $group['watering_interval_days'],
            'fertilizing_interval_days' => $group['fertilizing_interval_days'],
            'pest_check_interval_days' => $group['pest_check_interval_days'],
            'rain_skip_threshold_mm' => $group['rain_skip_threshold_mm'],
            'frost_temp_threshold_c' => $group['frost_temp_threshold_c'],
            'heat_extra_water_temp_c' => $group['heat_extra_water_temp_c'],
            'wind_protection_kmh' => $group['wind_protection_kmh'],
            'profile_group' => $profileGroup,
            'profile_label' => $group['profile_label'],
        ];
    }
}
